#!/bin/bash
#
#  This shell script is used on MacOS to launch OVITO in scripting mode.
#

# Get the directory this shell script is located in.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Run actual ovitos executable from sub-bundle and forward all command line parameters.
${DIR}/Ovito.app/Contents/MacOS/ovitos $@
